### PR TITLE
build for linux

### PR DESCRIPTION
**Pull request by dalandis**
build for linux

### CODE REVIEW

**Comment by Gregory-AM** [comment]
I'll be checking this PR later, in about 17 hours from now as I'm working on other projects.

But, looking though it, it looks good.

**Comment by JoshuaMarti** [comment]
I'm starting to wonder if we should remove README.rst, just to make maintaining the readme simpler, so we don't have to worry about updating them both.

**Comment by dalandis** [comment]
I think it would look better on a wiki.
If the wiki is really coming soon, it's better to wait.

**Comment by Gregory-AM** [comment]
> I think it would look better on a wiki. If the wiki is really coming soon, it's better to wait.

The Wiki currently has 8 pages, while the homepage (page 1) is about 75% completed.
I'm keeping a similar theme to Overviewer Documentation but updated and with what's new in Overviewer v1.20.

@JoshuaMarti, that's not a bad idea to remove the README.rst as it's ***not*** required for this repo. I'll be removing it in the next commit.

**Comment by JoshuaMarti** [comment]
We could probably just merge this for now and implement it into the Wiki, and maybe trim down the Readme when the Wiki goes live.

**Pull request closed without merging**
